version: "3.3"
services:

  django:
    build: .
    container_name: django
    command: gunicorn AlphaProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/usr/src/AlphaProject
      - ../staticfiles/:/home/AlphaProject/static/
    ports:
    - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - pgdb

  pgdb:
    image: postgres:13-alpine
    container_name: postgresdb
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    build: ../nginx
    container_name: django_nginx
    depends_on:
      - django
      - pgdb
    ports:
    - "80:80"
    volumes:
    - ../staticfiles/:/home/AlphaProject/static/

#  celery:
#    build: ./
#    container_name: celery
#    command: celery --app AlphaProject worker --loglevel=info
#    volumes:
#      - ../:/usr/src/AlphaProject
#    env_file:
#      - ../.env
#    depends_on:
#      - django
#      - redis
#
#  redis:
#    image: redis:5-alpine

volumes:
  pgdata: